sudo: required

language: python

services:
  - docker

before_install:
  # Debugging
  - echo Current path
  - pwd
  - echo Project dir contents
  - ls
  # Build docker image
  - docker build -t test_image -f test/Dockerfile .

script:
  # Run tests
  - docker run test_image -c "export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; python test/travis_test_script.py test/autotest_bot.py"