# language: python

# # sudo false implies containerized builds
# sudo: required

# services:
#   - docker

# # add the cloned directory to python path
# env: PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR

# # install libraries needed to run
# install:
#     - pip install s2clientprotocol async-timeout portpicker websockets aiohttp

# # run my unit tests
# script: 
#   python test/test_position.py
# script:
#   python test/test_unit.py
# script:
#   python test/test_units.py



sudo: required

language: python

services:
  - docker

before_install:  
  # Debugging
  - echo Current path
  - pwd
  - echo Project dir contents
  - ls
  # Build docker image
  - docker build -t test_image -f test/Dockerfile .

script:
  # Run tests
  # - docker run --name mytest test_image /root/run_tests.sh
  - docker run test_image -c "examples/protoss/cannon_rush.py"
  - docker run test_image -c "examples/protoss/threebase_voidray.py"
  - docker run test_image -c "examples/protoss/warpgate_push.py"

  - docker run test_image -c "examples/terran/cyclone_push.py"
  - docker run test_image -c "examples/terran/mass_reaper.py"
  - docker run test_image -c "examples/terran/onebase_battlecruiser.py"
  - docker run test_image -c "examples/terran/proxy_rax.py"
  - docker run test_image -c "examples/terran/ramp_wall.py"

  - docker run test_image -c "examples/zerg/hydralisk_push.py"
  - docker run test_image -c "examples/zerg/onebase_broodlord.py"
  - docker run test_image -c "examples/zerg/zerg_rush.py"